# Netlify configuration file

[build]
  # This command is run when Netlify builds the site.
  # For a static site with functions, it might be empty or a frontend build command.
  # If you have frontend build steps (e.g., for React, Vue, Svelte), put them here.
  # command = "npm run build" # Example if you have a frontend build script

  # Directory that contains the serverless functions.
  functions = "netlify/functions"

  # Directory to publish (your static frontend assets).
  # This should be where your index.html and other client-side files are.
  publish = "public"

# Optional: Redirects/Rewrites for cleaner API URLs
# For example, to make /api/register point to /.netlify/functions/register
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200 # Use 200 for function proxies

# We will use direct /.netlify/functions/function-name calls for now
# to avoid complexity with redirects until functions are working.

[dev]
  # Command to run when using `netlify dev`
  # This is often your frontend development server command
  # command = "npm run dev" # if your dev script starts a frontend server
  # For now, Netlify Dev will serve from 'publish' and run functions.
  # We might need to adjust this if we want `server.js` to run locally with `netlify dev` for Socket.IO later,
  # but for pure function conversion, this is okay.
  # targetPort = 3000 # If your local dev server (e.g. server.js) runs on 3000
  # port = 8888 # Port for Netlify Dev proxy
  # publish = "public" # Should match [build.publish]
  # functions = "netlify/functions" # Should match [build.functions]

# Note: For a Node.js app that's *not* purely serverless functions but a full server,
# the setup on Netlify is different and more complex, often involving adapters.
# We are proceeding with converting API routes to serverless functions.
